apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example
    is-fork: fork
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example-container
          image: ubuntu:precise-20151020
          ports:
            - containerPort: 80
---
apiVersion: fork.k8s.wantedly.com/v1beta1
kind: ForkManager
metadata:
  name: kubefork-manager
spec:
  ambassadorID: default
  headerKey: x-fork-identifier
  upstreams:
  - host: example.com
    original: example-service:8080