---
apiVersion: getambassador.io/v2
items:
  - apiVersion: getambassador.io
    kind: Mapping
    metadata:
      creationTimestamp: null
      name: mapping-not-related-to-fork
      namespace: ambassador
    spec:
      ambassador_id:
        - some-other-ambassador-id
      host: www.example.com
      prefix: /
      service: backend.example.com
      timeout_ms: 90000
kind: MappingList
metadata: {}

---
apiVersion: duplication.k8s.wantedly.com/v1beta1
items: null
kind: DeploymentCopyList
metadata: {}

---
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      name: some-service-name
      namespace: some-namespace
    spec:
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8081
      selector:
        app: some-app
        role: web
      type: ClusterIP
    status:
      loadBalancer: {}
kind: ServiceList
metadata: {}

---
apiVersion: fork.k8s.wantedly.com/v1beta1
items:
  - apiVersion: vsconfig.k8s.wantedly.com/v1beta1
    kind: VSConfig
    metadata:
      creationTimestamp: null
      name: some-service-name-some-identifier
      namespace: some-namespace
    spec:
      headerName: some-header-name
      headerValue: some-identifier
      host: some-service-name
      service: custom-routing-service-name
    status: {}
kind: VSConfigList
metadata: {}

---
apiVersion: fork.k8s.wantedly.com/v1beta1
items: []
kind: ForkList
metadata: {}

