---
apiVersion: networking.istio.io/v1beta1
items:
  - apiVersion: networking.istio.io/v1beta1
    kind: VirtualService
    metadata:
      creationTimestamp: null
      name: existing-virtual-service-name
      namespace: some-namespace
    spec:
      hosts:
        - some-service-name
    status: {}
kind: VirtualServiceList
metadata: {}

