# permissions for end users to edit forkmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: forkmanager-editor-role
rules:
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - forkmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - forkmanagers/status
  verbs:
  - get
