# permissions for end users to view forkmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: forkmanager-viewer-role
rules:
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - forkmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - forkmanagers/status
  verbs:
  - get
