---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - gverbs=get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - duplication.k8s.wantedly.com
  resources:
  - deploymentcopies
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - forkmanagers
  - forks
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - vsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - vsconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - vsconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - getambassador.io
  resources:
  - mappings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
