# permissions for end users to edit vsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vsconfig-editor-role
rules:
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - vsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - vsconfigs/status
  verbs:
  - get
