# permissions for end users to view vsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vsconfig-viewer-role
rules:
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - vsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fork.k8s.wantedly.com
  resources:
  - vsconfigs/status
  verbs:
  - get
